/* soapenrimaSoap11Proxy.h
   Generated by gSOAP 2.8.3 from enrima.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapenrimaSoap11Proxy_H
#define soapenrimaSoap11Proxy_H
#include "soapH.h"

class SOAP_CMAC enrimaSoap11Proxy : public soap
{ public:
	/// Endpoint URL of service 'enrimaSoap11Proxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	enrimaSoap11Proxy();
	/// Constructor with copy of another engine state
	enrimaSoap11Proxy(const struct soap&);
	/// Constructor with endpoint URL
	enrimaSoap11Proxy(const char *url);
	/// Constructor with engine input+output mode control
	enrimaSoap11Proxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	enrimaSoap11Proxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	enrimaSoap11Proxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~enrimaSoap11Proxy();
	/// Initializer used by constructors
	virtual	void enrimaSoap11Proxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Force close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'changeModelDataStatus' (returns error code or SOAP_OK)
	virtual	int changeModelDataStatus(_ns1__changeModelDataStatusRequest *ns1__changeModelDataStatusRequest, _ns1__changeModelDataStatusResponse *ns1__changeModelDataStatusResponse) { return changeModelDataStatus(NULL, NULL, ns1__changeModelDataStatusRequest, ns1__changeModelDataStatusResponse); }
	virtual	int changeModelDataStatus(const char *endpoint, const char *soap_action, _ns1__changeModelDataStatusRequest *ns1__changeModelDataStatusRequest, _ns1__changeModelDataStatusResponse *ns1__changeModelDataStatusResponse);

	/// Web service operation 'updateSolverStatus' (returns error code or SOAP_OK)
	virtual	int updateSolverStatus(_ns1__updateSolverStatusRequest *ns1__updateSolverStatusRequest, _ns1__updateSolverStatusResponse *ns1__updateSolverStatusResponse) { return updateSolverStatus(NULL, NULL, ns1__updateSolverStatusRequest, ns1__updateSolverStatusResponse); }
	virtual	int updateSolverStatus(const char *endpoint, const char *soap_action, _ns1__updateSolverStatusRequest *ns1__updateSolverStatusRequest, _ns1__updateSolverStatusResponse *ns1__updateSolverStatusResponse);

	/// Web service operation 'getAnalyses' (returns error code or SOAP_OK)
	virtual	int getAnalyses(_ns1__getAnalysesRequest *ns1__getAnalysesRequest, _ns1__getAnalysesResponse *ns1__getAnalysesResponse) { return getAnalyses(NULL, NULL, ns1__getAnalysesRequest, ns1__getAnalysesResponse); }
	virtual	int getAnalyses(const char *endpoint, const char *soap_action, _ns1__getAnalysesRequest *ns1__getAnalysesRequest, _ns1__getAnalysesResponse *ns1__getAnalysesResponse);

	/// Web service operation 'defineModelData' (returns error code or SOAP_OK)
	virtual	int defineModelData(_ns1__defineModelDataRequest *ns1__defineModelDataRequest, _ns1__defineModelDataResponse *ns1__defineModelDataResponse) { return defineModelData(NULL, NULL, ns1__defineModelDataRequest, ns1__defineModelDataResponse); }
	virtual	int defineModelData(const char *endpoint, const char *soap_action, _ns1__defineModelDataRequest *ns1__defineModelDataRequest, _ns1__defineModelDataResponse *ns1__defineModelDataResponse);

	/// Web service operation 'runScenario' (returns error code or SOAP_OK)
	virtual	int runScenario(_ns1__runScenarioRequest *ns1__runScenarioRequest, _ns1__runScenarioResponse *ns1__runScenarioResponse) { return runScenario(NULL, NULL, ns1__runScenarioRequest, ns1__runScenarioResponse); }
	virtual	int runScenario(const char *endpoint, const char *soap_action, _ns1__runScenarioRequest *ns1__runScenarioRequest, _ns1__runScenarioResponse *ns1__runScenarioResponse);

	/// Web service operation 'defineAnalysis' (returns error code or SOAP_OK)
	virtual	int defineAnalysis(_ns1__defineAnalysisRequest *ns1__defineAnalysisRequest, _ns1__defineAnalysisResponse *ns1__defineAnalysisResponse) { return defineAnalysis(NULL, NULL, ns1__defineAnalysisRequest, ns1__defineAnalysisResponse); }
	virtual	int defineAnalysis(const char *endpoint, const char *soap_action, _ns1__defineAnalysisRequest *ns1__defineAnalysisRequest, _ns1__defineAnalysisResponse *ns1__defineAnalysisResponse);

	/// Web service operation 'getPreference' (returns error code or SOAP_OK)
	virtual	int getPreference(_ns1__getPreferenceRequest *ns1__getPreferenceRequest, _ns1__getPreferenceResponse *ns1__getPreferenceResponse) { return getPreference(NULL, NULL, ns1__getPreferenceRequest, ns1__getPreferenceResponse); }
	virtual	int getPreference(const char *endpoint, const char *soap_action, _ns1__getPreferenceRequest *ns1__getPreferenceRequest, _ns1__getPreferenceResponse *ns1__getPreferenceResponse);

	/// Web service operation 'getEntityValues' (returns error code or SOAP_OK)
	virtual	int getEntityValues(_ns1__getEntityValuesRequest *ns1__getEntityValuesRequest, _ns1__getEntityValuesResponse *ns1__getEntityValuesResponse) { return getEntityValues(NULL, NULL, ns1__getEntityValuesRequest, ns1__getEntityValuesResponse); }
	virtual	int getEntityValues(const char *endpoint, const char *soap_action, _ns1__getEntityValuesRequest *ns1__getEntityValuesRequest, _ns1__getEntityValuesResponse *ns1__getEntityValuesResponse);

	/// Web service operation 'storeMainSet' (returns error code or SOAP_OK)
	virtual	int storeMainSet(_ns1__storeMainSetRequest *ns1__storeMainSetRequest, _ns1__storeMainSetResponse *ns1__storeMainSetResponse) { return storeMainSet(NULL, NULL, ns1__storeMainSetRequest, ns1__storeMainSetResponse); }
	virtual	int storeMainSet(const char *endpoint, const char *soap_action, _ns1__storeMainSetRequest *ns1__storeMainSetRequest, _ns1__storeMainSetResponse *ns1__storeMainSetResponse);

	/// Web service operation 'getSMS' (returns error code or SOAP_OK)
	virtual	int getSMS(_ns1__getSMSRequest *ns1__getSMSRequest, _ns1__getSMSResponse *ns1__getSMSResponse) { return getSMS(NULL, NULL, ns1__getSMSRequest, ns1__getSMSResponse); }
	virtual	int getSMS(const char *endpoint, const char *soap_action, _ns1__getSMSRequest *ns1__getSMSRequest, _ns1__getSMSResponse *ns1__getSMSResponse);

	/// Web service operation 'getSolution' (returns error code or SOAP_OK)
	virtual	int getSolution(_ns1__getSolutionRequest *ns1__getSolutionRequest, _ns1__getSolutionResponse *ns1__getSolutionResponse) { return getSolution(NULL, NULL, ns1__getSolutionRequest, ns1__getSolutionResponse); }
	virtual	int getSolution(const char *endpoint, const char *soap_action, _ns1__getSolutionRequest *ns1__getSolutionRequest, _ns1__getSolutionResponse *ns1__getSolutionResponse);

	/// Web service operation 'getBatchValues' (returns error code or SOAP_OK)
	virtual	int getBatchValues(_ns1__getBatchValuesRequest *ns1__getBatchValuesRequest, _ns1__getBatchValuesResponse *ns1__getBatchValuesResponse) { return getBatchValues(NULL, NULL, ns1__getBatchValuesRequest, ns1__getBatchValuesResponse); }
	virtual	int getBatchValues(const char *endpoint, const char *soap_action, _ns1__getBatchValuesRequest *ns1__getBatchValuesRequest, _ns1__getBatchValuesResponse *ns1__getBatchValuesResponse);

	/// Web service operation 'removeEntityValues' (returns error code or SOAP_OK)
	virtual	int removeEntityValues(_ns1__removeEntityValuesRequest *ns1__removeEntityValuesRequest, _ns1__removeEntityValuesResponse *ns1__removeEntityValuesResponse) { return removeEntityValues(NULL, NULL, ns1__removeEntityValuesRequest, ns1__removeEntityValuesResponse); }
	virtual	int removeEntityValues(const char *endpoint, const char *soap_action, _ns1__removeEntityValuesRequest *ns1__removeEntityValuesRequest, _ns1__removeEntityValuesResponse *ns1__removeEntityValuesResponse);

	/// Web service operation 'getDataSummary' (returns error code or SOAP_OK)
	virtual	int getDataSummary(_ns1__getDataSummaryRequest *ns1__getDataSummaryRequest, _ns1__getDataSummaryResponse *ns1__getDataSummaryResponse) { return getDataSummary(NULL, NULL, ns1__getDataSummaryRequest, ns1__getDataSummaryResponse); }
	virtual	int getDataSummary(const char *endpoint, const char *soap_action, _ns1__getDataSummaryRequest *ns1__getDataSummaryRequest, _ns1__getDataSummaryResponse *ns1__getDataSummaryResponse);

	/// Web service operation 'storeSolution' (returns error code or SOAP_OK)
	virtual	int storeSolution(_ns1__storeSolutionRequest *ns1__storeSolutionRequest, _ns1__storeSolutionResponse *ns1__storeSolutionResponse) { return storeSolution(NULL, NULL, ns1__storeSolutionRequest, ns1__storeSolutionResponse); }
	virtual	int storeSolution(const char *endpoint, const char *soap_action, _ns1__storeSolutionRequest *ns1__storeSolutionRequest, _ns1__storeSolutionResponse *ns1__storeSolutionResponse);

	/// Web service operation 'getSetMembers' (returns error code or SOAP_OK)
	virtual	int getSetMembers(_ns1__getSetMembersRequest *ns1__getSetMembersRequest, _ns1__getSetMembersResponse *ns1__getSetMembersResponse) { return getSetMembers(NULL, NULL, ns1__getSetMembersRequest, ns1__getSetMembersResponse); }
	virtual	int getSetMembers(const char *endpoint, const char *soap_action, _ns1__getSetMembersRequest *ns1__getSetMembersRequest, _ns1__getSetMembersResponse *ns1__getSetMembersResponse);

	/// Web service operation 'definePreference' (returns error code or SOAP_OK)
	virtual	int definePreference(_ns1__definePreferenceRequest *ns1__definePreferenceRequest, _ns1__definePreferenceResponse *ns1__definePreferenceResponse) { return definePreference(NULL, NULL, ns1__definePreferenceRequest, ns1__definePreferenceResponse); }
	virtual	int definePreference(const char *endpoint, const char *soap_action, _ns1__definePreferenceRequest *ns1__definePreferenceRequest, _ns1__definePreferenceResponse *ns1__definePreferenceResponse);

	/// Web service operation 'storeSetMembers' (returns error code or SOAP_OK)
	virtual	int storeSetMembers(_ns1__storeSetMembersRequest *ns1__storeSetMembersRequest, _ns1__storeSetMembersResponse *ns1__storeSetMembersResponse) { return storeSetMembers(NULL, NULL, ns1__storeSetMembersRequest, ns1__storeSetMembersResponse); }
	virtual	int storeSetMembers(const char *endpoint, const char *soap_action, _ns1__storeSetMembersRequest *ns1__storeSetMembersRequest, _ns1__storeSetMembersResponse *ns1__storeSetMembersResponse);

	/// Web service operation 'runSolver' (returns error code or SOAP_OK)
	virtual	int runSolver(_ns1__runSolverRequest *ns1__runSolverRequest, _ns1__runSolverResponse *ns1__runSolverResponse) { return runSolver(NULL, NULL, ns1__runSolverRequest, ns1__runSolverResponse); }
	virtual	int runSolver(const char *endpoint, const char *soap_action, _ns1__runSolverRequest *ns1__runSolverRequest, _ns1__runSolverResponse *ns1__runSolverResponse);

	/// Web service operation 'defineInstance' (returns error code or SOAP_OK)
	virtual	int defineInstance(_ns1__defineInstanceRequest *ns1__defineInstanceRequest, _ns1__defineInstanceResponse *ns1__defineInstanceResponse) { return defineInstance(NULL, NULL, ns1__defineInstanceRequest, ns1__defineInstanceResponse); }
	virtual	int defineInstance(const char *endpoint, const char *soap_action, _ns1__defineInstanceRequest *ns1__defineInstanceRequest, _ns1__defineInstanceResponse *ns1__defineInstanceResponse);

	/// Web service operation 'removeSetMembers' (returns error code or SOAP_OK)
	virtual	int removeSetMembers(_ns1__removeSetMembersRequest *ns1__removeSetMembersRequest, _ns1__removeSetMembersResponse *ns1__removeSetMembersResponse) { return removeSetMembers(NULL, NULL, ns1__removeSetMembersRequest, ns1__removeSetMembersResponse); }
	virtual	int removeSetMembers(const char *endpoint, const char *soap_action, _ns1__removeSetMembersRequest *ns1__removeSetMembersRequest, _ns1__removeSetMembersResponse *ns1__removeSetMembersResponse);

	/// Web service operation 'storeEntityValues' (returns error code or SOAP_OK)
	virtual	int storeEntityValues(_ns1__storeEntityValuesRequest *ns1__storeEntityValuesRequest, _ns1__storeEntityValuesResponse *ns1__storeEntityValuesResponse) { return storeEntityValues(NULL, NULL, ns1__storeEntityValuesRequest, ns1__storeEntityValuesResponse); }
	virtual	int storeEntityValues(const char *endpoint, const char *soap_action, _ns1__storeEntityValuesRequest *ns1__storeEntityValuesRequest, _ns1__storeEntityValuesResponse *ns1__storeEntityValuesResponse);

	/// Web service operation 'getSolverStatus' (returns error code or SOAP_OK)
	virtual	int getSolverStatus(_ns1__getSolverStatusRequest *ns1__getSolverStatusRequest, _ns1__getSolverStatusResponse *ns1__getSolverStatusResponse) { return getSolverStatus(NULL, NULL, ns1__getSolverStatusRequest, ns1__getSolverStatusResponse); }
	virtual	int getSolverStatus(const char *endpoint, const char *soap_action, _ns1__getSolverStatusRequest *ns1__getSolverStatusRequest, _ns1__getSolverStatusResponse *ns1__getSolverStatusResponse);
};
#endif
