/* soapenrimaSoap11Proxy.cpp
   Generated by gSOAP 2.8.3 from enrima.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapenrimaSoap11Proxy.h"

enrimaSoap11Proxy::enrimaSoap11Proxy()
{	enrimaSoap11Proxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

enrimaSoap11Proxy::enrimaSoap11Proxy(const struct soap &_soap) : soap(_soap)
{ }

enrimaSoap11Proxy::enrimaSoap11Proxy(const char *url)
{	enrimaSoap11Proxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

enrimaSoap11Proxy::enrimaSoap11Proxy(soap_mode iomode)
{	enrimaSoap11Proxy_init(iomode, iomode);
}

enrimaSoap11Proxy::enrimaSoap11Proxy(const char *url, soap_mode iomode)
{	enrimaSoap11Proxy_init(iomode, iomode);
	soap_endpoint = url;
}

enrimaSoap11Proxy::enrimaSoap11Proxy(soap_mode imode, soap_mode omode)
{	enrimaSoap11Proxy_init(imode, omode);
}

enrimaSoap11Proxy::~enrimaSoap11Proxy()
{ }

void enrimaSoap11Proxy::enrimaSoap11Proxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns2", "http://www.ime.iiasa.ac.at/model/spec", NULL, NULL},
	{"ns4", "http://www.ime.iiasa.ac.at/model/analysis", NULL, NULL},
	{"ns3", "http://www.ime.iiasa.ac.at/model/instance", NULL, NULL},
	{"ns1", "http://www.ime.iiasa.ac.at/enrima", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void enrimaSoap11Proxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void enrimaSoap11Proxy::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *enrimaSoap11Proxy::soap_header()
{	return this->header;
}

const SOAP_ENV__Fault *enrimaSoap11Proxy::soap_fault()
{	return this->fault;
}

const char *enrimaSoap11Proxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *enrimaSoap11Proxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int enrimaSoap11Proxy::soap_close_socket()
{	return soap_closesock(this);
}

void enrimaSoap11Proxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
void enrimaSoap11Proxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}

char *enrimaSoap11Proxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int enrimaSoap11Proxy::changeModelDataStatus(const char *endpoint, const char *soap_action, _ns1__changeModelDataStatusRequest *ns1__changeModelDataStatusRequest, _ns1__changeModelDataStatusResponse *ns1__changeModelDataStatusResponse)
{	struct soap *soap = this;
	struct __ns1__changeModelDataStatus soap_tmp___ns1__changeModelDataStatus;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__changeModelDataStatus.ns1__changeModelDataStatusRequest = ns1__changeModelDataStatusRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__changeModelDataStatus(soap, &soap_tmp___ns1__changeModelDataStatus);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__changeModelDataStatus(soap, &soap_tmp___ns1__changeModelDataStatus, "-ns1:changeModelDataStatus", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__changeModelDataStatus(soap, &soap_tmp___ns1__changeModelDataStatus, "-ns1:changeModelDataStatus", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__changeModelDataStatusResponse)
		return soap_closesock(soap);
	ns1__changeModelDataStatusResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__changeModelDataStatusResponse->soap_get(soap, "ns1:changeModelDataStatusResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::updateSolverStatus(const char *endpoint, const char *soap_action, _ns1__updateSolverStatusRequest *ns1__updateSolverStatusRequest, _ns1__updateSolverStatusResponse *ns1__updateSolverStatusResponse)
{	struct soap *soap = this;
	struct __ns1__updateSolverStatus soap_tmp___ns1__updateSolverStatus;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__updateSolverStatus.ns1__updateSolverStatusRequest = ns1__updateSolverStatusRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__updateSolverStatus(soap, &soap_tmp___ns1__updateSolverStatus);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__updateSolverStatus(soap, &soap_tmp___ns1__updateSolverStatus, "-ns1:updateSolverStatus", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__updateSolverStatus(soap, &soap_tmp___ns1__updateSolverStatus, "-ns1:updateSolverStatus", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__updateSolverStatusResponse)
		return soap_closesock(soap);
	ns1__updateSolverStatusResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__updateSolverStatusResponse->soap_get(soap, "ns1:updateSolverStatusResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::getAnalyses(const char *endpoint, const char *soap_action, _ns1__getAnalysesRequest *ns1__getAnalysesRequest, _ns1__getAnalysesResponse *ns1__getAnalysesResponse)
{	struct soap *soap = this;
	struct __ns1__getAnalyses soap_tmp___ns1__getAnalyses;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getAnalyses.ns1__getAnalysesRequest = ns1__getAnalysesRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getAnalyses(soap, &soap_tmp___ns1__getAnalyses);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getAnalyses(soap, &soap_tmp___ns1__getAnalyses, "-ns1:getAnalyses", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getAnalyses(soap, &soap_tmp___ns1__getAnalyses, "-ns1:getAnalyses", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getAnalysesResponse)
		return soap_closesock(soap);
	ns1__getAnalysesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getAnalysesResponse->soap_get(soap, "ns1:getAnalysesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::defineModelData(const char *endpoint, const char *soap_action, _ns1__defineModelDataRequest *ns1__defineModelDataRequest, _ns1__defineModelDataResponse *ns1__defineModelDataResponse)
{	struct soap *soap = this;
	struct __ns1__defineModelData soap_tmp___ns1__defineModelData;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__defineModelData.ns1__defineModelDataRequest = ns1__defineModelDataRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__defineModelData(soap, &soap_tmp___ns1__defineModelData);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__defineModelData(soap, &soap_tmp___ns1__defineModelData, "-ns1:defineModelData", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__defineModelData(soap, &soap_tmp___ns1__defineModelData, "-ns1:defineModelData", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__defineModelDataResponse)
		return soap_closesock(soap);
	ns1__defineModelDataResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__defineModelDataResponse->soap_get(soap, "ns1:defineModelDataResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::runScenario(const char *endpoint, const char *soap_action, _ns1__runScenarioRequest *ns1__runScenarioRequest, _ns1__runScenarioResponse *ns1__runScenarioResponse)
{	struct soap *soap = this;
	struct __ns1__runScenario soap_tmp___ns1__runScenario;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__runScenario.ns1__runScenarioRequest = ns1__runScenarioRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__runScenario(soap, &soap_tmp___ns1__runScenario);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__runScenario(soap, &soap_tmp___ns1__runScenario, "-ns1:runScenario", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__runScenario(soap, &soap_tmp___ns1__runScenario, "-ns1:runScenario", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__runScenarioResponse)
		return soap_closesock(soap);
	ns1__runScenarioResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__runScenarioResponse->soap_get(soap, "ns1:runScenarioResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::defineAnalysis(const char *endpoint, const char *soap_action, _ns1__defineAnalysisRequest *ns1__defineAnalysisRequest, _ns1__defineAnalysisResponse *ns1__defineAnalysisResponse)
{	struct soap *soap = this;
	struct __ns1__defineAnalysis soap_tmp___ns1__defineAnalysis;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__defineAnalysis.ns1__defineAnalysisRequest = ns1__defineAnalysisRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__defineAnalysis(soap, &soap_tmp___ns1__defineAnalysis);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__defineAnalysis(soap, &soap_tmp___ns1__defineAnalysis, "-ns1:defineAnalysis", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__defineAnalysis(soap, &soap_tmp___ns1__defineAnalysis, "-ns1:defineAnalysis", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__defineAnalysisResponse)
		return soap_closesock(soap);
	ns1__defineAnalysisResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__defineAnalysisResponse->soap_get(soap, "ns1:defineAnalysisResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::getPreference(const char *endpoint, const char *soap_action, _ns1__getPreferenceRequest *ns1__getPreferenceRequest, _ns1__getPreferenceResponse *ns1__getPreferenceResponse)
{	struct soap *soap = this;
	struct __ns1__getPreference soap_tmp___ns1__getPreference;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getPreference.ns1__getPreferenceRequest = ns1__getPreferenceRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getPreference(soap, &soap_tmp___ns1__getPreference);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getPreference(soap, &soap_tmp___ns1__getPreference, "-ns1:getPreference", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getPreference(soap, &soap_tmp___ns1__getPreference, "-ns1:getPreference", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getPreferenceResponse)
		return soap_closesock(soap);
	ns1__getPreferenceResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getPreferenceResponse->soap_get(soap, "ns1:getPreferenceResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::getEntityValues(const char *endpoint, const char *soap_action, _ns1__getEntityValuesRequest *ns1__getEntityValuesRequest, _ns1__getEntityValuesResponse *ns1__getEntityValuesResponse)
{	struct soap *soap = this;
	struct __ns1__getEntityValues soap_tmp___ns1__getEntityValues;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getEntityValues.ns1__getEntityValuesRequest = ns1__getEntityValuesRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getEntityValues(soap, &soap_tmp___ns1__getEntityValues);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getEntityValues(soap, &soap_tmp___ns1__getEntityValues, "-ns1:getEntityValues", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getEntityValues(soap, &soap_tmp___ns1__getEntityValues, "-ns1:getEntityValues", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getEntityValuesResponse)
		return soap_closesock(soap);
	ns1__getEntityValuesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getEntityValuesResponse->soap_get(soap, "ns1:getEntityValuesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::storeMainSet(const char *endpoint, const char *soap_action, _ns1__storeMainSetRequest *ns1__storeMainSetRequest, _ns1__storeMainSetResponse *ns1__storeMainSetResponse)
{	struct soap *soap = this;
	struct __ns1__storeMainSet soap_tmp___ns1__storeMainSet;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__storeMainSet.ns1__storeMainSetRequest = ns1__storeMainSetRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__storeMainSet(soap, &soap_tmp___ns1__storeMainSet);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__storeMainSet(soap, &soap_tmp___ns1__storeMainSet, "-ns1:storeMainSet", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__storeMainSet(soap, &soap_tmp___ns1__storeMainSet, "-ns1:storeMainSet", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__storeMainSetResponse)
		return soap_closesock(soap);
	ns1__storeMainSetResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__storeMainSetResponse->soap_get(soap, "ns1:storeMainSetResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::getSMS(const char *endpoint, const char *soap_action, _ns1__getSMSRequest *ns1__getSMSRequest, _ns1__getSMSResponse *ns1__getSMSResponse)
{	struct soap *soap = this;
	struct __ns1__getSMS soap_tmp___ns1__getSMS;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getSMS.ns1__getSMSRequest = ns1__getSMSRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getSMS(soap, &soap_tmp___ns1__getSMS);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getSMS(soap, &soap_tmp___ns1__getSMS, "-ns1:getSMS", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getSMS(soap, &soap_tmp___ns1__getSMS, "-ns1:getSMS", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getSMSResponse)
		return soap_closesock(soap);
	ns1__getSMSResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getSMSResponse->soap_get(soap, "ns1:getSMSResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::getSolution(const char *endpoint, const char *soap_action, _ns1__getSolutionRequest *ns1__getSolutionRequest, _ns1__getSolutionResponse *ns1__getSolutionResponse)
{	struct soap *soap = this;
	struct __ns1__getSolution soap_tmp___ns1__getSolution;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getSolution.ns1__getSolutionRequest = ns1__getSolutionRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getSolution(soap, &soap_tmp___ns1__getSolution);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getSolution(soap, &soap_tmp___ns1__getSolution, "-ns1:getSolution", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getSolution(soap, &soap_tmp___ns1__getSolution, "-ns1:getSolution", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getSolutionResponse)
		return soap_closesock(soap);
	ns1__getSolutionResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getSolutionResponse->soap_get(soap, "ns1:getSolutionResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::getBatchValues(const char *endpoint, const char *soap_action, _ns1__getBatchValuesRequest *ns1__getBatchValuesRequest, _ns1__getBatchValuesResponse *ns1__getBatchValuesResponse)
{	struct soap *soap = this;
	struct __ns1__getBatchValues soap_tmp___ns1__getBatchValues;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getBatchValues.ns1__getBatchValuesRequest = ns1__getBatchValuesRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getBatchValues(soap, &soap_tmp___ns1__getBatchValues);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getBatchValues(soap, &soap_tmp___ns1__getBatchValues, "-ns1:getBatchValues", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getBatchValues(soap, &soap_tmp___ns1__getBatchValues, "-ns1:getBatchValues", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getBatchValuesResponse)
		return soap_closesock(soap);
	ns1__getBatchValuesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getBatchValuesResponse->soap_get(soap, "ns1:getBatchValuesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::removeEntityValues(const char *endpoint, const char *soap_action, _ns1__removeEntityValuesRequest *ns1__removeEntityValuesRequest, _ns1__removeEntityValuesResponse *ns1__removeEntityValuesResponse)
{	struct soap *soap = this;
	struct __ns1__removeEntityValues soap_tmp___ns1__removeEntityValues;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__removeEntityValues.ns1__removeEntityValuesRequest = ns1__removeEntityValuesRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__removeEntityValues(soap, &soap_tmp___ns1__removeEntityValues);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__removeEntityValues(soap, &soap_tmp___ns1__removeEntityValues, "-ns1:removeEntityValues", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__removeEntityValues(soap, &soap_tmp___ns1__removeEntityValues, "-ns1:removeEntityValues", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__removeEntityValuesResponse)
		return soap_closesock(soap);
	ns1__removeEntityValuesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__removeEntityValuesResponse->soap_get(soap, "ns1:removeEntityValuesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::getDataSummary(const char *endpoint, const char *soap_action, _ns1__getDataSummaryRequest *ns1__getDataSummaryRequest, _ns1__getDataSummaryResponse *ns1__getDataSummaryResponse)
{	struct soap *soap = this;
	struct __ns1__getDataSummary soap_tmp___ns1__getDataSummary;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getDataSummary.ns1__getDataSummaryRequest = ns1__getDataSummaryRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getDataSummary(soap, &soap_tmp___ns1__getDataSummary);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getDataSummary(soap, &soap_tmp___ns1__getDataSummary, "-ns1:getDataSummary", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getDataSummary(soap, &soap_tmp___ns1__getDataSummary, "-ns1:getDataSummary", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getDataSummaryResponse)
		return soap_closesock(soap);
	ns1__getDataSummaryResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getDataSummaryResponse->soap_get(soap, "ns1:getDataSummaryResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::storeSolution(const char *endpoint, const char *soap_action, _ns1__storeSolutionRequest *ns1__storeSolutionRequest, _ns1__storeSolutionResponse *ns1__storeSolutionResponse)
{	struct soap *soap = this;
	struct __ns1__storeSolution soap_tmp___ns1__storeSolution;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__storeSolution.ns1__storeSolutionRequest = ns1__storeSolutionRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__storeSolution(soap, &soap_tmp___ns1__storeSolution);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__storeSolution(soap, &soap_tmp___ns1__storeSolution, "-ns1:storeSolution", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__storeSolution(soap, &soap_tmp___ns1__storeSolution, "-ns1:storeSolution", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__storeSolutionResponse)
		return soap_closesock(soap);
	ns1__storeSolutionResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__storeSolutionResponse->soap_get(soap, "ns1:storeSolutionResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::getSetMembers(const char *endpoint, const char *soap_action, _ns1__getSetMembersRequest *ns1__getSetMembersRequest, _ns1__getSetMembersResponse *ns1__getSetMembersResponse)
{	struct soap *soap = this;
	struct __ns1__getSetMembers soap_tmp___ns1__getSetMembers;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getSetMembers.ns1__getSetMembersRequest = ns1__getSetMembersRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getSetMembers(soap, &soap_tmp___ns1__getSetMembers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getSetMembers(soap, &soap_tmp___ns1__getSetMembers, "-ns1:getSetMembers", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getSetMembers(soap, &soap_tmp___ns1__getSetMembers, "-ns1:getSetMembers", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getSetMembersResponse)
		return soap_closesock(soap);
	ns1__getSetMembersResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getSetMembersResponse->soap_get(soap, "ns1:getSetMembersResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::definePreference(const char *endpoint, const char *soap_action, _ns1__definePreferenceRequest *ns1__definePreferenceRequest, _ns1__definePreferenceResponse *ns1__definePreferenceResponse)
{	struct soap *soap = this;
	struct __ns1__definePreference soap_tmp___ns1__definePreference;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__definePreference.ns1__definePreferenceRequest = ns1__definePreferenceRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__definePreference(soap, &soap_tmp___ns1__definePreference);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__definePreference(soap, &soap_tmp___ns1__definePreference, "-ns1:definePreference", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__definePreference(soap, &soap_tmp___ns1__definePreference, "-ns1:definePreference", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__definePreferenceResponse)
		return soap_closesock(soap);
	ns1__definePreferenceResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__definePreferenceResponse->soap_get(soap, "ns1:definePreferenceResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::storeSetMembers(const char *endpoint, const char *soap_action, _ns1__storeSetMembersRequest *ns1__storeSetMembersRequest, _ns1__storeSetMembersResponse *ns1__storeSetMembersResponse)
{	struct soap *soap = this;
	struct __ns1__storeSetMembers soap_tmp___ns1__storeSetMembers;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__storeSetMembers.ns1__storeSetMembersRequest = ns1__storeSetMembersRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__storeSetMembers(soap, &soap_tmp___ns1__storeSetMembers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__storeSetMembers(soap, &soap_tmp___ns1__storeSetMembers, "-ns1:storeSetMembers", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__storeSetMembers(soap, &soap_tmp___ns1__storeSetMembers, "-ns1:storeSetMembers", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__storeSetMembersResponse)
		return soap_closesock(soap);
	ns1__storeSetMembersResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__storeSetMembersResponse->soap_get(soap, "ns1:storeSetMembersResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::runSolver(const char *endpoint, const char *soap_action, _ns1__runSolverRequest *ns1__runSolverRequest, _ns1__runSolverResponse *ns1__runSolverResponse)
{	struct soap *soap = this;
	struct __ns1__runSolver soap_tmp___ns1__runSolver;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__runSolver.ns1__runSolverRequest = ns1__runSolverRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__runSolver(soap, &soap_tmp___ns1__runSolver);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__runSolver(soap, &soap_tmp___ns1__runSolver, "-ns1:runSolver", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__runSolver(soap, &soap_tmp___ns1__runSolver, "-ns1:runSolver", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__runSolverResponse)
		return soap_closesock(soap);
	ns1__runSolverResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__runSolverResponse->soap_get(soap, "ns1:runSolverResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::defineInstance(const char *endpoint, const char *soap_action, _ns1__defineInstanceRequest *ns1__defineInstanceRequest, _ns1__defineInstanceResponse *ns1__defineInstanceResponse)
{	struct soap *soap = this;
	struct __ns1__defineInstance soap_tmp___ns1__defineInstance;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__defineInstance.ns1__defineInstanceRequest = ns1__defineInstanceRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__defineInstance(soap, &soap_tmp___ns1__defineInstance);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__defineInstance(soap, &soap_tmp___ns1__defineInstance, "-ns1:defineInstance", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__defineInstance(soap, &soap_tmp___ns1__defineInstance, "-ns1:defineInstance", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__defineInstanceResponse)
		return soap_closesock(soap);
	ns1__defineInstanceResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__defineInstanceResponse->soap_get(soap, "ns1:defineInstanceResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::removeSetMembers(const char *endpoint, const char *soap_action, _ns1__removeSetMembersRequest *ns1__removeSetMembersRequest, _ns1__removeSetMembersResponse *ns1__removeSetMembersResponse)
{	struct soap *soap = this;
	struct __ns1__removeSetMembers soap_tmp___ns1__removeSetMembers;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__removeSetMembers.ns1__removeSetMembersRequest = ns1__removeSetMembersRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__removeSetMembers(soap, &soap_tmp___ns1__removeSetMembers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__removeSetMembers(soap, &soap_tmp___ns1__removeSetMembers, "-ns1:removeSetMembers", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__removeSetMembers(soap, &soap_tmp___ns1__removeSetMembers, "-ns1:removeSetMembers", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__removeSetMembersResponse)
		return soap_closesock(soap);
	ns1__removeSetMembersResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__removeSetMembersResponse->soap_get(soap, "ns1:removeSetMembersResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::storeEntityValues(const char *endpoint, const char *soap_action, _ns1__storeEntityValuesRequest *ns1__storeEntityValuesRequest, _ns1__storeEntityValuesResponse *ns1__storeEntityValuesResponse)
{	struct soap *soap = this;
	struct __ns1__storeEntityValues soap_tmp___ns1__storeEntityValues;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__storeEntityValues.ns1__storeEntityValuesRequest = ns1__storeEntityValuesRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__storeEntityValues(soap, &soap_tmp___ns1__storeEntityValues);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__storeEntityValues(soap, &soap_tmp___ns1__storeEntityValues, "-ns1:storeEntityValues", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__storeEntityValues(soap, &soap_tmp___ns1__storeEntityValues, "-ns1:storeEntityValues", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__storeEntityValuesResponse)
		return soap_closesock(soap);
	ns1__storeEntityValuesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__storeEntityValuesResponse->soap_get(soap, "ns1:storeEntityValuesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::getSolverStatus(const char *endpoint, const char *soap_action, _ns1__getSolverStatusRequest *ns1__getSolverStatusRequest, _ns1__getSolverStatusResponse *ns1__getSolverStatusResponse)
{	struct soap *soap = this;
	struct __ns1__getSolverStatus soap_tmp___ns1__getSolverStatus;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/soap/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getSolverStatus.ns1__getSolverStatusRequest = ns1__getSolverStatusRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getSolverStatus(soap, &soap_tmp___ns1__getSolverStatus);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getSolverStatus(soap, &soap_tmp___ns1__getSolverStatus, "-ns1:getSolverStatus", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getSolverStatus(soap, &soap_tmp___ns1__getSolverStatus, "-ns1:getSolverStatus", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getSolverStatusResponse)
		return soap_closesock(soap);
	ns1__getSolverStatusResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getSolverStatusResponse->soap_get(soap, "ns1:getSolverStatusResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
